/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type LogEntryTransformer from '#transformers/log_entry_transformer'
import type NoteTransformer from '#transformers/note_transformer'
import type UserSettingTransformer from '#transformers/user_setting_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type LogEntry = InferData<LogEntryTransformer>
  export namespace LogEntry {
    export type Variants = InferVariants<LogEntryTransformer>
  }
  export type Note = InferData<NoteTransformer>
  export namespace Note {
    export type Variants = InferVariants<NoteTransformer>
  }
  export type UserSetting = InferData<UserSettingTransformer>
  export namespace UserSetting {
    export type Variants = InferVariants<UserSettingTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
